version = '2'

[linters]
default = 'none'
enable = [
  'dogsled',
  'goconst',
  'gocritic',
  'gocyclo',
  'goprintffuncname',
  'gosec',
  'govet',
  'ineffassign',
  'misspell',
  'nakedret',
  'rowserrcheck',
  'staticcheck',
  'unconvert',
  'unparam',
  'unused',
  'whitespace'
]

[linters.settings]
[linters.settings.goconst]
min-len = 5
min-occurrences = 5

[linters.exclusions]
generated = 'lax'
presets = [
  'comments',
  'common-false-positives',
  'legacy',
  'std-error-handling'
]
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[[linters.exclusions.rules]]
linters = [
  'staticcheck'
]
path = '_test.go'
text = 'ST1003: should not use underscores in Go names;'

[[linters.exclusions.rules]]
linters = [
  'gosec'
]
text = 'G402: TLS MinVersion too low.'

[[linters.exclusions.rules]]
linters = [
  'gosec'
]
text = 'G115: integer overflow conversion'

[formatters]
enable = [
  'goimports'
]

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]
